import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import MoviesList from '../components/MoviesList';
import titleStyles from '../styles/siteTitle.module.css';

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Movie Wallet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={titleStyles.site}>
        <section className={titleStyles.wrapper}>
          <div className={titleStyles.top}>Movie Wallet</div>
          <div className={titleStyles.bottom} aria-hidden="true">Movie Wallet</div>
        </section>
      </div>
        <div>
            <MoviesList />
        </div>
    </div>
  )
}